from __future__ import annotations

import os
import subprocess
import sys
from pathlib import Path

from ops.core.compose import AUTOGENERATED_COMMENT

REPO_ROOT = Path(__file__).resolve().parents[1]


def test_generate_compose_cli_smoke(tmp_path: Path) -> None:
    services_dir = tmp_path / "services"
    services_dir.mkdir()
    (tmp_path / ".env").write_text(
        "DB_POSTGRES_VERSION=18\n"
        "DB_DEFAULT_POSTGRES_PASSWORD=secret\n",
        encoding="utf-8",
    )
    (services_dir / ".env.test").write_text(
        "POSTGRES_USER=admin\n"
        "POSTGRES_PASSWORD=pa$word\n"
        "POSTGRES_PORT=5401\n",
        encoding="utf-8",
    )

    env = os.environ.copy()
    env["PYTHONPATH"] = str(REPO_ROOT)

    result = subprocess.run(
        [sys.executable, "-m", "ops.cli", "generate-compose"],
        cwd=tmp_path,
        env=env,
        capture_output=True,
        text=True,
        check=False,
    )

    assert result.returncode == 0, result.stderr
    compose_path = tmp_path / "compose.yaml"
    assert compose_path.exists()
    assert compose_path.read_text(encoding="utf-8").startswith(
        f"{AUTOGENERATED_COMMENT}\n"
    )
