from __future__ import annotations

import subprocess
import sys
from pathlib import Path

import pytest

from ops.commands import add as add_command
from ops.commands import apply as apply_command
from ops.commands import sizes as sizes_command
from ops.cli import generate_compose
from ops.core.compose import AUTOGENERATED_COMMENT
from ops.core.models import ServiceConfig
from ops.operations import services as services_ops

REPO_ROOT = Path(__file__).resolve().parents[1]
PUBLIC_COMMANDS = ("add", "remove", "apply", "backup", "dump", "restore", "sizes", "autobackup")
STUB_COMMANDS = ("remove", "backup", "dump", "restore", "autobackup")


def test_generate_compose_internal_api_smoke(tmp_path: Path) -> None:
    services_dir = tmp_path / "services"
    services_dir.mkdir()
    (tmp_path / ".env").write_text(
        "DB_POSTGRES_VERSION=18\n"
        "DB_DEFAULT_POSTGRES_PASSWORD=secret\n",
        encoding="utf-8",
    )
    (services_dir / ".env.test").write_text(
        "POSTGRES_USER=admin\n"
        "POSTGRES_PASSWORD=pa$word\n"
        "POSTGRES_PORT=5401\n",
        encoding="utf-8",
    )

    compose_path = generate_compose(tmp_path)

    assert compose_path.exists()
    assert compose_path.read_text(encoding="utf-8").startswith(
        f"{AUTOGENERATED_COMMENT}\n"
    )


@pytest.mark.parametrize(
    ("argv", "cwd"),
    (
        ([sys.executable, "-m", "ops.cli", "--help"], REPO_ROOT),
        ([sys.executable, "ops/cli.py", "--help"], REPO_ROOT),
    ),
)
def test_help_works_for_module_and_script_entrypoints(
    argv: list[str],
    cwd: Path,
) -> None:
    result = subprocess.run(
        argv,
        cwd=cwd,
        capture_output=True,
        text=True,
        check=False,
    )

    assert result.returncode == 0, result.stderr
    assert "Usage" in result.stdout
    for command_name in PUBLIC_COMMANDS:
        assert command_name in result.stdout
    assert "generate-compose" not in result.stdout


@pytest.mark.parametrize("command_name", STUB_COMMANDS)
def test_stub_commands_are_silent_success(command_name: str) -> None:
    result = subprocess.run(
        [sys.executable, "-m", "ops.cli", command_name],
        cwd=REPO_ROOT,
        capture_output=True,
        text=True,
        check=False,
    )

    assert result.returncode == 0
    assert result.stdout == ""
    assert result.stderr == ""


def test_add_decline_leaves_materialized_files_and_skips_runtime(
    monkeypatch: pytest.MonkeyPatch,
    tmp_path: Path,
) -> None:
    services_dir = tmp_path / "services"
    services_dir.mkdir()
    (tmp_path / ".env").write_text(
        "DB_POSTGRES_VERSION=18\n"
        "DB_DEFAULT_POSTGRES_PASSWORD=secret\n",
        encoding="utf-8",
    )

    monkeypatch.chdir(tmp_path)
    monkeypatch.setattr(add_command.typer, "confirm", lambda *args, **kwargs: False)
    monkeypatch.setattr(add_command, "compose_up", lambda *args, **kwargs: (_ for _ in ()).throw(AssertionError("compose_up should not run")))
    monkeypatch.setattr(add_command, "wait_for_pg_ready", lambda *args, **kwargs: (_ for _ in ()).throw(AssertionError("wait_for_pg_ready should not run")))

    add_command.add("demo", port=None, password="pw1")

    assert (tmp_path / "services" / ".env.demo").exists()
    assert (tmp_path / "data" / "demo").exists()
    assert (tmp_path / "compose.yaml").exists()


def test_add_confirm_runs_compose_and_wait(
    monkeypatch: pytest.MonkeyPatch,
    tmp_path: Path,
) -> None:
    services_dir = tmp_path / "services"
    services_dir.mkdir()
    (tmp_path / ".env").write_text(
        "DB_POSTGRES_VERSION=18\n"
        "DB_DEFAULT_POSTGRES_PASSWORD=secret\n",
        encoding="utf-8",
    )

    compose_calls: list[tuple[Path, str | None]] = []
    wait_calls: list[tuple[str, str, str]] = []

    monkeypatch.chdir(tmp_path)
    monkeypatch.setattr(add_command.typer, "confirm", lambda *args, **kwargs: True)
    monkeypatch.setattr(
        add_command,
        "compose_up",
        lambda project_root, service=None: compose_calls.append((project_root, service)),
    )
    monkeypatch.setattr(
        add_command,
        "wait_for_pg_ready",
        lambda container_name, service_name, postgres_user, **kwargs: wait_calls.append(
            (container_name, service_name, postgres_user)
        ),
    )

    add_command.add("demo", port=None, password="pw1")

    assert compose_calls == [(tmp_path, "demo")]
    assert wait_calls == [("demo", "demo", "admin")]


def test_apply_decline_keeps_prepared_files_and_skips_runtime(
    monkeypatch: pytest.MonkeyPatch,
    tmp_path: Path,
) -> None:
    services_dir = tmp_path / "services"
    services_dir.mkdir()
    (tmp_path / ".env").write_text("DB_POSTGRES_VERSION=18\n", encoding="utf-8")
    (services_dir / ".env.demo").write_text(
        "POSTGRES_USER=admin\n"
        "POSTGRES_PASSWORD=secret\n"
        "POSTGRES_PORT=5401\n",
        encoding="utf-8",
    )

    monkeypatch.chdir(tmp_path)
    monkeypatch.setattr(apply_command.typer, "confirm", lambda *args, **kwargs: False)
    monkeypatch.setattr(apply_command, "compose_up", lambda *args, **kwargs: (_ for _ in ()).throw(AssertionError("compose_up should not run")))
    monkeypatch.setattr(apply_command, "sync_service_password", lambda *args, **kwargs: (_ for _ in ()).throw(AssertionError("sync should not run")))
    monkeypatch.setattr(apply_command, "wait_for_pg_ready", lambda *args, **kwargs: (_ for _ in ()).throw(AssertionError("wait should not run")))

    apply_command.apply()

    assert (tmp_path / "data" / "demo").exists()
    assert (tmp_path / "compose.yaml").exists()


def test_apply_confirm_runs_runtime_and_password_sync(
    monkeypatch: pytest.MonkeyPatch,
    tmp_path: Path,
) -> None:
    services_dir = tmp_path / "services"
    services_dir.mkdir()
    (tmp_path / ".env").write_text("DB_POSTGRES_VERSION=18\n", encoding="utf-8")
    (services_dir / ".env.demo").write_text(
        "POSTGRES_USER=admin\n"
        "POSTGRES_PASSWORD=secret\n"
        "POSTGRES_PORT=5401\n",
        encoding="utf-8",
    )

    compose_calls: list[tuple[Path, str | None]] = []
    sync_calls: list[str] = []
    wait_calls: list[tuple[str, str, str]] = []

    monkeypatch.chdir(tmp_path)
    monkeypatch.setattr(apply_command.typer, "confirm", lambda *args, **kwargs: True)
    monkeypatch.setattr(apply_command, "compose_up", lambda project_root, service=None: compose_calls.append((project_root, service)))
    monkeypatch.setattr(apply_command, "container_exists", lambda name: True)
    monkeypatch.setattr(apply_command, "container_is_running", lambda name: True)
    monkeypatch.setattr(
        apply_command,
        "wait_for_pg_ready",
        lambda container_name, service_name, postgres_user, **kwargs: wait_calls.append(
            (container_name, service_name, postgres_user)
        ),
    )
    monkeypatch.setattr(
        apply_command,
        "sync_service_password",
        lambda container_name, service_config: sync_calls.append(container_name),
    )
    monkeypatch.setattr(services_ops, "container_exists", lambda name: False)

    apply_command.apply()

    assert compose_calls == [(tmp_path, None)]
    assert wait_calls == [("demo", "demo", "admin")]
    assert sync_calls == ["demo"]


def test_sizes_logs_when_no_services_found(
    monkeypatch: pytest.MonkeyPatch,
    caplog: pytest.LogCaptureFixture,
    tmp_path: Path,
) -> None:
    monkeypatch.chdir(tmp_path)
    monkeypatch.setattr(sizes_command, "load_all_service_configs", lambda project_root: [])

    with caplog.at_level("INFO"):
        sizes_command.sizes()

    assert "No services found" in caplog.text


def test_sizes_reports_running_and_stopped_services(
    monkeypatch: pytest.MonkeyPatch,
    caplog: pytest.LogCaptureFixture,
    tmp_path: Path,
) -> None:
    configs = [
        ServiceConfig(
            name="running_demo",
            env_path=tmp_path / "services" / ".env.running_demo",
            postgres_user="admin",
            postgres_password="secret",
            postgres_port=5401,
        ),
        ServiceConfig(
            name="stopped_demo",
            env_path=tmp_path / "services" / ".env.stopped_demo",
            postgres_user="admin",
            postgres_password="secret",
            postgres_port=5402,
        ),
    ]

    monkeypatch.chdir(tmp_path)
    monkeypatch.setattr(sizes_command, "load_all_service_configs", lambda project_root: configs)
    monkeypatch.setattr(
        sizes_command,
        "container_exists",
        lambda name: True,
    )
    monkeypatch.setattr(
        sizes_command,
        "container_is_running",
        lambda name: name == "running_demo",
    )
    monkeypatch.setattr(
        sizes_command,
        "query_database_size",
        lambda container_name, service_config: 7861951,
    )

    with caplog.at_level("INFO"):
        sizes_command.sizes()

    assert "running_demo: 0.01 GB" in caplog.text
    assert "stopped_demo: stopped, start the service first" in caplog.text


def test_sizes_propagates_query_errors(
    monkeypatch: pytest.MonkeyPatch,
    tmp_path: Path,
) -> None:
    configs = [
        ServiceConfig(
            name="broken_demo",
            env_path=tmp_path / "services" / ".env.broken_demo",
            postgres_user="admin",
            postgres_password="secret",
            postgres_port=5401,
        ),
    ]

    monkeypatch.chdir(tmp_path)
    monkeypatch.setattr(sizes_command, "load_all_service_configs", lambda project_root: configs)
    monkeypatch.setattr(sizes_command, "container_exists", lambda name: True)
    monkeypatch.setattr(sizes_command, "container_is_running", lambda name: True)
    monkeypatch.setattr(
        sizes_command,
        "query_database_size",
        lambda container_name, service_config: (_ for _ in ()).throw(
            ValueError("broken size query")
        ),
    )

    with pytest.raises(ValueError, match="broken size query"):
        sizes_command.sizes()
