from __future__ import annotations

from pathlib import Path

import pytest

from ops.core.compose import (
    AUTOGENERATED_COMMENT,
    build_compose,
    compute_shm_size_bytes,
    read_mem_total_bytes,
    resolve_postgres_data_dir,
    validate_unique_ports,
    write_compose,
)
from ops.core.models import GlobalConfig, ServiceConfig


def test_build_compose_includes_raw_env_file_and_derived_db(monkeypatch: pytest.MonkeyPatch, tmp_path: Path) -> None:
    monkeypatch.setattr("ops.core.compose.read_mem_total_bytes", lambda: 1000)

    compose = build_compose(
        GlobalConfig(postgres_version="18", default_postgres_password=None),
        [
            ServiceConfig(
                name="test",
                env_path=tmp_path / "services" / ".env.test",
                postgres_user="admin",
                postgres_password="secret",
                postgres_port=5401,
                max_connections=10000,
                memory_limit="512M",
                cpu_limit="1.50",
            )
        ],
    )

    service = compose["services"]["test"]

    assert service["env_file"] == [{"path": "./services/.env.test", "format": "raw"}]
    assert service["environment"] == {"POSTGRES_DB": "test"}
    assert service["volumes"] == ["./data/test:/var/lib/postgresql/18/docker"]
    assert service["shm_size"] == 900
    assert service["command"] == ["postgres", "-c", "max_connections=10000"]
    assert service["deploy"] == {
        "resources": {"limits": {"memory": "512M", "cpus": "1.50"}}
    }


def test_build_compose_uses_same_shm_size_for_all_services(monkeypatch: pytest.MonkeyPatch, tmp_path: Path) -> None:
    monkeypatch.setattr("ops.core.compose.read_mem_total_bytes", lambda: 2000)

    compose = build_compose(
        GlobalConfig(postgres_version="18", default_postgres_password=None),
        [
            ServiceConfig(
                name="alpha",
                env_path=tmp_path / "services" / ".env.alpha",
                postgres_user="admin",
                postgres_password="secret",
                postgres_port=5401,
            ),
            ServiceConfig(
                name="beta",
                env_path=tmp_path / "services" / ".env.beta",
                postgres_user="admin",
                postgres_password="secret",
                postgres_port=5402,
            ),
        ],
    )

    assert compose["services"]["alpha"]["shm_size"] == 1800
    assert compose["services"]["beta"]["shm_size"] == 1800


def test_validate_unique_ports_rejects_conflicts(tmp_path: Path) -> None:
    service_configs = [
        ServiceConfig(
            name="alpha",
            env_path=tmp_path / "services" / ".env.alpha",
            postgres_user="admin",
            postgres_password="secret",
            postgres_port=5401,
        ),
        ServiceConfig(
            name="beta",
            env_path=tmp_path / "services" / ".env.beta",
            postgres_user="admin",
            postgres_password="secret",
            postgres_port=5401,
        ),
    ]

    with pytest.raises(ValueError, match="5401"):
        validate_unique_ports(service_configs)


def test_resolve_postgres_data_dir_tracks_major_version() -> None:
    assert resolve_postgres_data_dir("18") == "/var/lib/postgresql/18/docker"
    assert resolve_postgres_data_dir("18.3") == "/var/lib/postgresql/18/docker"
    assert resolve_postgres_data_dir("17") == "/var/lib/postgresql/data"


def test_write_compose_prepends_autogenerated_comment(tmp_path: Path) -> None:
    compose_path = write_compose(tmp_path, {"services": {"test": {"image": "postgres:18"}}})

    contents = compose_path.read_text(encoding="utf-8")
    assert contents.startswith(f"{AUTOGENERATED_COMMENT}\n")


def test_read_mem_total_bytes_parses_memtotal(tmp_path: Path) -> None:
    meminfo_path = tmp_path / "meminfo"
    meminfo_path.write_text("MemTotal:       1024 kB\n", encoding="utf-8")

    assert read_mem_total_bytes(meminfo_path) == 1024 * 1024
    assert compute_shm_size_bytes(1000) == 900
