from __future__ import annotations

import subprocess
import sys
from pathlib import Path

import pytest

from ops.commands import add as add_command
from ops.commands import apply as apply_command
from ops.commands import autobackup as autobackup_command
from ops.commands import backup as backup_command
from ops.commands import dump as dump_command
from ops.commands import remove as remove_command
from ops.commands import restore as restore_command
from ops.commands import sizes as sizes_command
from ops.cli import generate_compose
from ops.core.compose import AUTOGENERATED_COMMENT
from ops.core.models import ServiceConfig
from ops.operations import backup as backup_ops
from ops.operations import restore as restore_ops

REPO_ROOT = Path(__file__).resolve().parents[1]
PUBLIC_COMMANDS = ("add", "remove", "apply", "backup", "dump", "restore", "sizes", "autobackup")


def test_generate_compose_internal_api_smoke(tmp_path: Path) -> None:
    services_dir = tmp_path / "services"
    services_dir.mkdir()
    (tmp_path / ".env").write_text(
        "DB_POSTGRES_VERSION=18\n"
        "DB_DEFAULT_POSTGRES_PASSWORD=secret\n",
        encoding="utf-8",
    )
    (services_dir / ".env.test").write_text(
        "POSTGRES_USER=admin\n"
        "POSTGRES_PASSWORD=pa$word\n"
        "POSTGRES_PORT=5401\n",
        encoding="utf-8",
    )

    compose_path = generate_compose(tmp_path)

    assert compose_path.exists()
    assert compose_path.read_text(encoding="utf-8").startswith(
        f"{AUTOGENERATED_COMMENT}\n"
    )


@pytest.mark.parametrize(
    ("argv", "cwd"),
    (
        ([sys.executable, "-m", "ops.cli", "--help"], REPO_ROOT),
        ([sys.executable, "ops/cli.py", "--help"], REPO_ROOT),
    ),
)
def test_help_works_for_module_and_script_entrypoints(
    argv: list[str],
    cwd: Path,
) -> None:
    result = subprocess.run(
        argv,
        cwd=cwd,
        capture_output=True,
        text=True,
        check=False,
    )

    assert result.returncode == 0, result.stderr
    assert "Usage" in result.stdout
    for command_name in PUBLIC_COMMANDS:
        assert command_name in result.stdout
    assert "generate-compose" not in result.stdout


def test_autobackup_help_shows_subcommands() -> None:
    result = subprocess.run(
        [sys.executable, "-m", "ops.cli", "autobackup", "--help"],
        cwd=REPO_ROOT,
        capture_output=True,
        text=True,
        check=False,
    )

    assert result.returncode == 0, result.stderr
    for command_name in ("install", "uninstall", "status", "test", "logs"):
        assert command_name in result.stdout


def test_add_decline_leaves_materialized_files_and_skips_runtime(
    monkeypatch: pytest.MonkeyPatch,
    tmp_path: Path,
) -> None:
    services_dir = tmp_path / "services"
    services_dir.mkdir()
    (tmp_path / ".env").write_text(
        "DB_POSTGRES_VERSION=18\n"
        "DB_DEFAULT_POSTGRES_PASSWORD=secret\n",
        encoding="utf-8",
    )

    monkeypatch.chdir(tmp_path)
    monkeypatch.setattr(add_command.typer, "confirm", lambda *args, **kwargs: False)
    monkeypatch.setattr(add_command, "compose_up", lambda *args, **kwargs: (_ for _ in ()).throw(AssertionError("compose_up should not run")))
    monkeypatch.setattr(add_command, "wait_for_pg_ready", lambda *args, **kwargs: (_ for _ in ()).throw(AssertionError("wait_for_pg_ready should not run")))

    add_command.add("demo", port=None, password="pw1")

    assert (tmp_path / "services" / ".env.demo").exists()
    assert (tmp_path / "data" / "demo").exists()
    assert (tmp_path / "compose.yaml").exists()


def test_add_confirm_runs_compose_and_wait(
    monkeypatch: pytest.MonkeyPatch,
    tmp_path: Path,
) -> None:
    services_dir = tmp_path / "services"
    services_dir.mkdir()
    (tmp_path / ".env").write_text(
        "DB_POSTGRES_VERSION=18\n"
        "DB_DEFAULT_POSTGRES_PASSWORD=secret\n",
        encoding="utf-8",
    )

    compose_calls: list[tuple[Path, str | None]] = []
    wait_calls: list[tuple[str, str, str]] = []

    monkeypatch.chdir(tmp_path)
    monkeypatch.setattr(add_command.typer, "confirm", lambda *args, **kwargs: True)
    monkeypatch.setattr(
        add_command,
        "compose_up",
        lambda project_root, service=None: compose_calls.append((project_root, service)),
    )
    monkeypatch.setattr(
        add_command,
        "wait_for_pg_ready",
        lambda container_name, service_name, postgres_user, **kwargs: wait_calls.append(
            (container_name, service_name, postgres_user)
        ),
    )

    add_command.add("demo", port=None, password="pw1")

    assert compose_calls == [(tmp_path, "demo")]
    assert wait_calls == [("demo", "demo", "admin")]


def test_apply_decline_keeps_prepared_files_and_skips_runtime(
    monkeypatch: pytest.MonkeyPatch,
    tmp_path: Path,
) -> None:
    services_dir = tmp_path / "services"
    services_dir.mkdir()
    (tmp_path / ".env").write_text("DB_POSTGRES_VERSION=18\n", encoding="utf-8")
    (services_dir / ".env.demo").write_text(
        "POSTGRES_USER=admin\n"
        "POSTGRES_PASSWORD=secret\n"
        "POSTGRES_PORT=5401\n",
        encoding="utf-8",
    )

    monkeypatch.chdir(tmp_path)
    monkeypatch.setattr(apply_command.typer, "confirm", lambda *args, **kwargs: False)
    monkeypatch.setattr(apply_command, "compose_up", lambda *args, **kwargs: (_ for _ in ()).throw(AssertionError("compose_up should not run")))
    monkeypatch.setattr(apply_command, "sync_service_password", lambda *args, **kwargs: (_ for _ in ()).throw(AssertionError("sync should not run")))
    monkeypatch.setattr(apply_command, "wait_for_pg_ready", lambda *args, **kwargs: (_ for _ in ()).throw(AssertionError("wait should not run")))

    apply_command.apply()

    assert (tmp_path / "data" / "demo").exists()
    assert (tmp_path / "compose.yaml").exists()


def test_apply_confirm_runs_runtime_and_password_sync(
    monkeypatch: pytest.MonkeyPatch,
    tmp_path: Path,
) -> None:
    services_dir = tmp_path / "services"
    services_dir.mkdir()
    (tmp_path / ".env").write_text("DB_POSTGRES_VERSION=18\n", encoding="utf-8")
    (services_dir / ".env.demo").write_text(
        "POSTGRES_USER=admin\n"
        "POSTGRES_PASSWORD=secret\n"
        "POSTGRES_PORT=5401\n",
        encoding="utf-8",
    )

    compose_calls: list[tuple[Path, str | None]] = []
    sync_calls: list[str] = []
    wait_calls: list[tuple[str, str, str]] = []

    monkeypatch.chdir(tmp_path)
    monkeypatch.setattr(apply_command.typer, "confirm", lambda *args, **kwargs: True)
    monkeypatch.setattr(apply_command, "compose_up", lambda project_root, service=None: compose_calls.append((project_root, service)))
    monkeypatch.setattr(apply_command, "container_is_running", lambda name: True)
    monkeypatch.setattr(
        apply_command,
        "wait_for_pg_ready",
        lambda container_name, service_name, postgres_user, **kwargs: wait_calls.append(
            (container_name, service_name, postgres_user)
        ),
    )
    monkeypatch.setattr(
        apply_command,
        "sync_service_password",
        lambda container_name, service_config: sync_calls.append(container_name),
    )
    apply_command.apply()

    assert compose_calls == [(tmp_path, None)]
    assert wait_calls == [("demo", "demo", "admin")]
    assert sync_calls == ["demo"]


def test_remove_missing_service_logs_existing_services(
    monkeypatch: pytest.MonkeyPatch,
    caplog: pytest.LogCaptureFixture,
    tmp_path: Path,
) -> None:
    services_dir = tmp_path / "services"
    services_dir.mkdir()
    (services_dir / ".env.alpha").write_text(
        "POSTGRES_USER=admin\n"
        "POSTGRES_PASSWORD=secret\n"
        "POSTGRES_PORT=5401\n",
        encoding="utf-8",
    )

    monkeypatch.chdir(tmp_path)
    with caplog.at_level("INFO"):
        remove_command.remove("demo", force=False)

    assert "Service demo was not found" in caplog.text
    assert "Existing services: alpha" in caplog.text


def test_remove_decline_on_initial_confirmation_leaves_assets(
    monkeypatch: pytest.MonkeyPatch,
    tmp_path: Path,
) -> None:
    services_dir = tmp_path / "services"
    services_dir.mkdir()
    env_path = services_dir / ".env.demo"
    env_path.write_text(
        "POSTGRES_USER=admin\n"
        "POSTGRES_PASSWORD=secret\n"
        "POSTGRES_PORT=5401\n",
        encoding="utf-8",
    )
    data_dir = tmp_path / "data" / "demo"
    data_dir.mkdir(parents=True)
    (data_dir / "db.bin").write_bytes(b"abc")

    monkeypatch.chdir(tmp_path)
    monkeypatch.setattr(remove_command.typer, "confirm", lambda *args, **kwargs: False)
    monkeypatch.setattr(
        remove_command,
        "docker_rm_force",
        lambda *args, **kwargs: (_ for _ in ()).throw(AssertionError("docker_rm_force should not run")),
    )
    monkeypatch.setattr(
        remove_command,
        "regenerate_compose_for_current_services",
        lambda *args, **kwargs: (_ for _ in ()).throw(
            AssertionError("compose regeneration should not run")
        ),
    )

    remove_command.remove("demo", force=False)

    assert env_path.exists()
    assert data_dir.exists()


def test_remove_name_mismatch_leaves_assets(
    monkeypatch: pytest.MonkeyPatch,
    tmp_path: Path,
) -> None:
    services_dir = tmp_path / "services"
    services_dir.mkdir()
    env_path = services_dir / ".env.demo"
    env_path.write_text(
        "POSTGRES_USER=admin\n"
        "POSTGRES_PASSWORD=secret\n"
        "POSTGRES_PORT=5401\n",
        encoding="utf-8",
    )
    data_dir = tmp_path / "data" / "demo"
    data_dir.mkdir(parents=True)

    prompts = iter(["wrong-name"])

    monkeypatch.chdir(tmp_path)
    monkeypatch.setattr(remove_command.typer, "confirm", lambda *args, **kwargs: True)
    monkeypatch.setattr(
        remove_command.typer,
        "prompt",
        lambda *args, **kwargs: next(prompts),
    )

    remove_command.remove("demo", force=False)

    assert env_path.exists()
    assert data_dir.exists()


def test_remove_delete_word_mismatch_leaves_assets(
    monkeypatch: pytest.MonkeyPatch,
    tmp_path: Path,
) -> None:
    services_dir = tmp_path / "services"
    services_dir.mkdir()
    env_path = services_dir / ".env.demo"
    env_path.write_text(
        "POSTGRES_USER=admin\n"
        "POSTGRES_PASSWORD=secret\n"
        "POSTGRES_PORT=5401\n",
        encoding="utf-8",
    )
    data_dir = tmp_path / "data" / "demo"
    data_dir.mkdir(parents=True)

    prompts = iter(["demo", "WRONG"])

    monkeypatch.chdir(tmp_path)
    monkeypatch.setattr(remove_command.typer, "confirm", lambda *args, **kwargs: True)
    monkeypatch.setattr(
        remove_command.typer,
        "prompt",
        lambda *args, **kwargs: next(prompts),
    )

    remove_command.remove("demo", force=False)

    assert env_path.exists()
    assert data_dir.exists()


def test_remove_force_removes_assets_and_writes_empty_compose(
    monkeypatch: pytest.MonkeyPatch,
    tmp_path: Path,
) -> None:
    services_dir = tmp_path / "services"
    services_dir.mkdir()
    (tmp_path / ".env").write_text("DB_POSTGRES_VERSION=18\n", encoding="utf-8")
    env_path = services_dir / ".env.demo"
    env_path.write_text(
        "POSTGRES_USER=admin\n"
        "POSTGRES_PASSWORD=secret\n"
        "POSTGRES_PORT=5401\n",
        encoding="utf-8",
    )
    data_dir = tmp_path / "data" / "demo"
    data_dir.mkdir(parents=True)
    (data_dir / "db.bin").write_bytes(b"abc")

    removed_containers: list[str] = []

    monkeypatch.chdir(tmp_path)
    monkeypatch.setattr(remove_command, "container_exists", lambda name: True)
    monkeypatch.setattr(
        remove_command,
        "docker_rm_force",
        lambda name: removed_containers.append(name),
    )

    remove_command.remove("demo", force=True)

    assert removed_containers == ["demo"]
    assert not env_path.exists()
    assert not data_dir.exists()
    assert (tmp_path / "compose.yaml").read_text(encoding="utf-8") == (
        f"{AUTOGENERATED_COMMENT}\nservices: {{}}\n"
    )


def test_remove_force_keeps_other_services_in_compose(
    monkeypatch: pytest.MonkeyPatch,
    tmp_path: Path,
) -> None:
    services_dir = tmp_path / "services"
    services_dir.mkdir()
    (tmp_path / ".env").write_text("DB_POSTGRES_VERSION=18\n", encoding="utf-8")
    (services_dir / ".env.alpha").write_text(
        "POSTGRES_USER=admin\n"
        "POSTGRES_PASSWORD=alpha\n"
        "POSTGRES_PORT=5401\n",
        encoding="utf-8",
    )
    (services_dir / ".env.beta").write_text(
        "POSTGRES_USER=admin\n"
        "POSTGRES_PASSWORD=beta\n"
        "POSTGRES_PORT=5402\n",
        encoding="utf-8",
    )
    (tmp_path / "data" / "alpha").mkdir(parents=True)
    (tmp_path / "data" / "beta").mkdir(parents=True)

    monkeypatch.chdir(tmp_path)
    monkeypatch.setattr(remove_command, "container_exists", lambda name: False)

    remove_command.remove("beta", force=True)

    compose_text = (tmp_path / "compose.yaml").read_text(encoding="utf-8")
    assert "alpha:" in compose_text
    assert "beta:" not in compose_text


def test_dump_logs_when_container_is_not_running(
    monkeypatch: pytest.MonkeyPatch,
    caplog: pytest.LogCaptureFixture,
    tmp_path: Path,
) -> None:
    services_dir = tmp_path / "services"
    services_dir.mkdir()
    (services_dir / ".env.demo").write_text(
        "POSTGRES_USER=admin\n"
        "POSTGRES_PASSWORD=secret\n"
        "POSTGRES_PORT=5401\n",
        encoding="utf-8",
    )

    monkeypatch.chdir(tmp_path)
    monkeypatch.setattr(dump_command, "container_is_running", lambda name: False)

    with caplog.at_level("INFO"):
        dump_command.dump("demo")

    assert "demo: service container is not running" in caplog.text
    assert not (tmp_path / "dumps").exists()


def test_dump_rejects_invalid_backup_format(
    monkeypatch: pytest.MonkeyPatch,
    tmp_path: Path,
) -> None:
    services_dir = tmp_path / "services"
    services_dir.mkdir()
    (services_dir / ".env.demo").write_text(
        "POSTGRES_USER=admin\n"
        "POSTGRES_PASSWORD=secret\n"
        "POSTGRES_PORT=5401\n"
        "POSTGRES_BACKUP_FORMAT=.zip\n",
        encoding="utf-8",
    )

    monkeypatch.chdir(tmp_path)
    monkeypatch.setattr(dump_command, "container_is_running", lambda name: True)
    monkeypatch.setattr(dump_command, "query_database_size", lambda *args, **kwargs: 1000)

    with pytest.raises(ValueError, match="POSTGRES_BACKUP_FORMAT"):
        dump_command.dump("demo")


def test_dump_logs_when_disk_space_is_insufficient(
    monkeypatch: pytest.MonkeyPatch,
    caplog: pytest.LogCaptureFixture,
    tmp_path: Path,
) -> None:
    services_dir = tmp_path / "services"
    services_dir.mkdir()
    (services_dir / ".env.demo").write_text(
        "POSTGRES_USER=admin\n"
        "POSTGRES_PASSWORD=secret\n"
        "POSTGRES_PORT=5401\n",
        encoding="utf-8",
    )

    class FakeDiskUsage:
        free = 100

    monkeypatch.chdir(tmp_path)
    monkeypatch.setattr(dump_command, "container_is_running", lambda name: True)
    monkeypatch.setattr(dump_command, "query_database_size", lambda *args, **kwargs: 1000)
    monkeypatch.setattr(dump_command.shutil, "disk_usage", lambda path: FakeDiskUsage())
    monkeypatch.setattr(
        dump_command,
        "_write_gzip_dump",
        lambda *args, **kwargs: (_ for _ in ()).throw(
            AssertionError("dump writer should not run")
        ),
    )

    with caplog.at_level("INFO"):
        dump_command.dump("demo")

    assert "not enough free space for dump" in caplog.text
    assert list((tmp_path / "dumps").glob("*")) == []


def test_dump_writes_plain_file_when_format_is_sql(
    monkeypatch: pytest.MonkeyPatch,
    tmp_path: Path,
) -> None:
    services_dir = tmp_path / "services"
    services_dir.mkdir()
    (services_dir / ".env.demo").write_text(
        "POSTGRES_USER=admin\n"
        "POSTGRES_PASSWORD=secret\n"
        "POSTGRES_PORT=5401\n"
        "POSTGRES_BACKUP_FORMAT=.sql\n",
        encoding="utf-8",
    )

    monkeypatch.chdir(tmp_path)
    monkeypatch.setattr(dump_command, "container_is_running", lambda name: True)
    monkeypatch.setattr(dump_command, "query_database_size", lambda *args, **kwargs: 1000)

    def fake_write_plain(container_name, service_config, dump_path):
        dump_path.write_bytes(b"plain dump")

    monkeypatch.setattr(dump_command, "_write_plain_dump", fake_write_plain)

    dump_command.dump("demo")

    dump_files = list((tmp_path / "dumps").glob("demo_*.sql"))
    assert len(dump_files) == 1
    assert dump_files[0].read_bytes() == b"plain dump"


def test_dump_writes_gzip_file_by_default(
    monkeypatch: pytest.MonkeyPatch,
    tmp_path: Path,
) -> None:
    services_dir = tmp_path / "services"
    services_dir.mkdir()
    (services_dir / ".env.demo").write_text(
        "POSTGRES_USER=admin\n"
        "POSTGRES_PASSWORD=secret\n"
        "POSTGRES_PORT=5401\n",
        encoding="utf-8",
    )

    monkeypatch.chdir(tmp_path)
    monkeypatch.setattr(dump_command, "container_is_running", lambda name: True)
    monkeypatch.setattr(dump_command, "query_database_size", lambda *args, **kwargs: 1000)

    def fake_write_gzip(container_name, service_config, dump_path):
        dump_path.write_bytes(b"gzip dump")

    monkeypatch.setattr(dump_command, "_write_gzip_dump", fake_write_gzip)

    dump_command.dump("demo")

    dump_files = list((tmp_path / "dumps").glob("demo_*.sql.gz"))
    assert len(dump_files) == 1
    assert dump_files[0].read_bytes() == b"gzip dump"


def test_dump_removes_partial_file_on_writer_failure(
    monkeypatch: pytest.MonkeyPatch,
    tmp_path: Path,
) -> None:
    services_dir = tmp_path / "services"
    services_dir.mkdir()
    (services_dir / ".env.demo").write_text(
        "POSTGRES_USER=admin\n"
        "POSTGRES_PASSWORD=secret\n"
        "POSTGRES_PORT=5401\n",
        encoding="utf-8",
    )

    monkeypatch.chdir(tmp_path)
    monkeypatch.setattr(dump_command, "container_is_running", lambda name: True)
    monkeypatch.setattr(dump_command, "query_database_size", lambda *args, **kwargs: 1000)

    def fake_write_gzip(container_name, service_config, dump_path):
        dump_path.write_bytes(b"partial")
        raise RuntimeError("dump failed")

    monkeypatch.setattr(dump_command, "_write_gzip_dump", fake_write_gzip)

    with pytest.raises(RuntimeError, match="dump failed"):
        dump_command.dump("demo")

    assert list((tmp_path / "dumps").glob("*")) == []


def test_backup_fails_fast_when_runtime_critical_settings_are_missing(
    monkeypatch: pytest.MonkeyPatch,
    tmp_path: Path,
) -> None:
    (tmp_path / ".env").write_text(
        "DB_POSTGRES_VERSION=18\n"
        "DB_REMOTE_HOST=2.26.53.128\n"
        "DB_REMOTE_USER=root\n"
        "DB_REMOTE_PASSWORD=secret\n"
        "DB_REMOTE_BACKUP_PATH=/root/backups\n",
        encoding="utf-8",
    )

    monkeypatch.chdir(tmp_path)

    with pytest.raises(ValueError, match="DB_BACKUP_TIMEOUT_SECONDS"):
        backup_command.backup(None)

    assert (tmp_path / "backup.log").exists()


def test_backup_logs_when_no_services_are_selected(
    monkeypatch: pytest.MonkeyPatch,
    caplog: pytest.LogCaptureFixture,
    tmp_path: Path,
) -> None:
    (tmp_path / ".env").write_text(
        "DB_POSTGRES_VERSION=18\n"
        "DB_REMOTE_HOST=2.26.53.128\n"
        "DB_REMOTE_USER=root\n"
        "DB_REMOTE_PASSWORD=secret\n"
        "DB_REMOTE_BACKUP_PATH=/root/backups\n"
        "DB_BACKUP_TIMEOUT_SECONDS=60\n"
        "DB_BACKUP_MAX_DAYS=30\n"
        "DB_BACKUP_MAX_FILES=14\n",
        encoding="utf-8",
    )

    monkeypatch.chdir(tmp_path)
    monkeypatch.setattr(backup_command, "backup_candidates", lambda *args, **kwargs: [])

    with caplog.at_level("INFO"):
        backup_command.backup(None)

    assert "No services selected for backup" in caplog.text
    assert "No services selected for backup" in (tmp_path / "backup.log").read_text(encoding="utf-8")


def test_backup_stopped_container_fails_whole_command_and_logs_traceback(
    monkeypatch: pytest.MonkeyPatch,
    tmp_path: Path,
) -> None:
    (tmp_path / ".env").write_text(
        "DB_POSTGRES_VERSION=18\n"
        "DB_REMOTE_HOST=2.26.53.128\n"
        "DB_REMOTE_USER=root\n"
        "DB_REMOTE_PASSWORD=secret\n"
        "DB_REMOTE_BACKUP_PATH=/root/backups\n"
        "DB_BACKUP_TIMEOUT_SECONDS=60\n"
        "DB_BACKUP_MAX_DAYS=30\n"
        "DB_BACKUP_MAX_FILES=14\n",
        encoding="utf-8",
    )

    cfg = ServiceConfig(
        name="demo",
        env_path=tmp_path / "services" / ".env.demo",
        postgres_user="admin",
        postgres_password="secret",
        postgres_port=5401,
    )

    class FakeSession:
        def __enter__(self):
            return self

        def __exit__(self, exc_type, exc, tb):
            return None

        def set_timeout(self, timeout_seconds):
            pass

    monkeypatch.chdir(tmp_path)
    monkeypatch.setattr(backup_command, "backup_candidates", lambda *args, **kwargs: [cfg])
    monkeypatch.setattr(backup_command, "open_remote_session", lambda *args, **kwargs: FakeSession())
    monkeypatch.setattr(
        backup_command,
        "stream_backup_to_remote",
        lambda *args, **kwargs: (_ for _ in ()).throw(RuntimeError("demo: service container is not running")),
    )

    with pytest.raises(RuntimeError, match="service container is not running"):
        backup_command.backup(None)

    assert "Backup failed" in (tmp_path / "backup.log").read_text(encoding="utf-8")


def test_backup_skips_disabled_named_service_as_noop(
    monkeypatch: pytest.MonkeyPatch,
    caplog: pytest.LogCaptureFixture,
    tmp_path: Path,
) -> None:
    services_dir = tmp_path / "services"
    services_dir.mkdir()
    (tmp_path / ".env").write_text(
        "DB_POSTGRES_VERSION=18\n"
        "DB_REMOTE_HOST=2.26.53.128\n"
        "DB_REMOTE_USER=root\n"
        "DB_REMOTE_PASSWORD=secret\n"
        "DB_REMOTE_BACKUP_PATH=/root/backups\n"
        "DB_BACKUP_TIMEOUT_SECONDS=60\n"
        "DB_BACKUP_MAX_DAYS=30\n"
        "DB_BACKUP_MAX_FILES=14\n",
        encoding="utf-8",
    )
    (services_dir / ".env.demo").write_text(
        "POSTGRES_USER=admin\n"
        "POSTGRES_PASSWORD=secret\n"
        "POSTGRES_PORT=5401\n"
        "POSTGRES_BACKUP_DISABLED=1\n",
        encoding="utf-8",
    )

    monkeypatch.chdir(tmp_path)

    with caplog.at_level("INFO"):
        backup_command.backup("demo")

    assert "No services selected for backup" in caplog.text


def test_backup_success_logs_summary_and_rotation_warning(
    monkeypatch: pytest.MonkeyPatch,
    caplog: pytest.LogCaptureFixture,
    tmp_path: Path,
) -> None:
    (tmp_path / ".env").write_text(
        "DB_POSTGRES_VERSION=18\n"
        "DB_REMOTE_HOST=2.26.53.128\n"
        "DB_REMOTE_USER=root\n"
        "DB_REMOTE_PASSWORD=secret\n"
        "DB_REMOTE_BACKUP_PATH=/root/backups\n"
        "DB_BACKUP_TIMEOUT_SECONDS=60\n"
        "DB_BACKUP_MAX_DAYS=30\n"
        "DB_BACKUP_MAX_FILES=14\n",
        encoding="utf-8",
    )

    cfg = ServiceConfig(
        name="demo",
        env_path=tmp_path / "services" / ".env.demo",
        postgres_user="admin",
        postgres_password="secret",
        postgres_port=5401,
    )

    class FakeSession:
        def __enter__(self):
            return self

        def __exit__(self, exc_type, exc, tb):
            return None

        def set_timeout(self, timeout_seconds):
            pass

    result = backup_ops.BackupResult(
        service_name="demo",
        remote_dir="/root/backups/host/demo",
        filename="demo_2026-04-14_12-30.sql.gz",
        dump_format=".sql.gz",
        size_bytes=123,
        tmp_cleaned_count=2,
    )

    monkeypatch.chdir(tmp_path)
    monkeypatch.setattr(backup_command, "backup_candidates", lambda *args, **kwargs: [cfg])
    monkeypatch.setattr(backup_command, "open_remote_session", lambda *args, **kwargs: FakeSession())
    monkeypatch.setattr(backup_command, "stream_backup_to_remote", lambda *args, **kwargs: result)
    monkeypatch.setattr(
        backup_command,
        "rotate_remote_backups",
        lambda *args, **kwargs: (_ for _ in ()).throw(RuntimeError("rotation failed")),
    )

    with caplog.at_level("INFO"):
        backup_command.backup(None)

    assert "demo: uploaded demo_2026-04-14_12-30.sql.gz" in caplog.text
    assert "demo: rotation failed" in caplog.text
    log_text = (tmp_path / "backup.log").read_text(encoding="utf-8")
    assert "Backup finished: selected=1 uploaded=1 tmp_cleaned=2 rotation_warnings=1" in log_text


def test_autobackup_install_logs_installed_state(
    monkeypatch: pytest.MonkeyPatch,
    caplog: pytest.LogCaptureFixture,
    tmp_path: Path,
) -> None:
    monkeypatch.chdir(tmp_path)
    monkeypatch.setattr(
        autobackup_command,
        "install_autobackup",
        lambda project_root: (True, False),
    )

    with caplog.at_level("INFO"):
        autobackup_command.install()

    assert "Backup cron installed: yes" in caplog.text
    assert "Metrics cron installed: no" in caplog.text


def test_autobackup_uninstall_logs_removed_counts(
    monkeypatch: pytest.MonkeyPatch,
    caplog: pytest.LogCaptureFixture,
    tmp_path: Path,
) -> None:
    monkeypatch.chdir(tmp_path)
    monkeypatch.setattr(
        autobackup_command,
        "uninstall_autobackup",
        lambda project_root: (1, 2),
    )

    with caplog.at_level("INFO"):
        autobackup_command.uninstall()

    assert "Removed backup cron jobs: 1" in caplog.text
    assert "Removed metrics cron jobs: 2" in caplog.text


def test_autobackup_status_logs_current_state(
    monkeypatch: pytest.MonkeyPatch,
    caplog: pytest.LogCaptureFixture,
    tmp_path: Path,
) -> None:
    monkeypatch.chdir(tmp_path)
    monkeypatch.setattr(
        autobackup_command,
        "build_autobackup_status",
        lambda project_root: autobackup_command.AutobackupStatus(
            backup_enabled=True,
            backup_schedule="*/5 * * * *",
            metrics_enabled=True,
            metrics_interval_minutes=5,
            backup_job_installed=True,
            metrics_job_installed=False,
            service_backup_flags=[("alpha", True), ("beta", False)],
        ),
    )

    with caplog.at_level("INFO"):
        autobackup_command.status()

    assert "Backup enabled: yes" in caplog.text
    assert "Metrics cron installed: no" in caplog.text
    assert "service alpha: backup enabled" in caplog.text
    assert "service beta: backup disabled" in caplog.text


def test_autobackup_test_runs_backup_now(
    monkeypatch: pytest.MonkeyPatch,
    tmp_path: Path,
) -> None:
    monkeypatch.chdir(tmp_path)
    calls: list[str | None] = []
    monkeypatch.setattr(autobackup_command, "backup_command", lambda name=None: calls.append(name))

    autobackup_command.test()

    assert calls == [None]


def test_autobackup_logs_shows_tail_or_missing_file(
    monkeypatch: pytest.MonkeyPatch,
    caplog: pytest.LogCaptureFixture,
    tmp_path: Path,
) -> None:
    monkeypatch.chdir(tmp_path)
    monkeypatch.setattr(autobackup_command, "read_backup_log_tail", lambda project_root: "")
    with caplog.at_level("INFO"):
        autobackup_command.logs()
    assert "No backup log found" in caplog.text

    caplog.clear()
    monkeypatch.setattr(autobackup_command, "read_backup_log_tail", lambda project_root: "line 1\nline 2")
    with caplog.at_level("INFO"):
        autobackup_command.logs()
    assert "line 1" in caplog.text
    assert "line 2" in caplog.text


def test_restore_path_mode_uses_sql_file_and_force_skips_confirmation(
    monkeypatch: pytest.MonkeyPatch,
    tmp_path: Path,
) -> None:
    services_dir = tmp_path / "services"
    services_dir.mkdir()
    sql_path = tmp_path / "dump.sql"
    sql_path.write_text("SELECT 1;", encoding="utf-8")
    (services_dir / ".env.demo").write_text(
        "POSTGRES_USER=admin\n"
        "POSTGRES_PASSWORD=secret\n"
        "POSTGRES_PORT=5401\n",
        encoding="utf-8",
    )

    calls: list[tuple[str, str]] = []

    monkeypatch.chdir(tmp_path)
    monkeypatch.setattr(restore_command, "container_is_running", lambda name: True)
    monkeypatch.setattr(restore_command, "query_database_size", lambda *args, **kwargs: 1024)
    monkeypatch.setattr(
        restore_command,
        "terminate_service_connections",
        lambda container_name, postgres_user, database_name: calls.append(("terminate", database_name)),
    )
    monkeypatch.setattr(
        restore_command,
        "drop_and_recreate_service_database",
        lambda container_name, postgres_user, database_name: calls.append(("recreate", database_name)),
    )
    monkeypatch.setattr(
        restore_command,
        "restore_sql_file",
        lambda container_name, postgres_user, database_name, local_sql_path: calls.append(("sql", str(local_sql_path))),
    )
    monkeypatch.setattr(
        restore_command,
        "restore_gzip_file",
        lambda *args, **kwargs: (_ for _ in ()).throw(AssertionError("gzip restore should not run")),
    )

    restore_command.restore("demo", str(sql_path), force=True)

    assert calls == [
        ("terminate", "demo"),
        ("recreate", "demo"),
        ("sql", str(sql_path)),
    ]


def test_restore_stopped_container_logs_and_returns(
    monkeypatch: pytest.MonkeyPatch,
    caplog: pytest.LogCaptureFixture,
    tmp_path: Path,
) -> None:
    services_dir = tmp_path / "services"
    services_dir.mkdir()
    sql_path = tmp_path / "dump.sql"
    sql_path.write_text("SELECT 1;", encoding="utf-8")
    (services_dir / ".env.demo").write_text(
        "POSTGRES_USER=admin\n"
        "POSTGRES_PASSWORD=secret\n"
        "POSTGRES_PORT=5401\n",
        encoding="utf-8",
    )

    monkeypatch.chdir(tmp_path)
    monkeypatch.setattr(restore_command, "container_is_running", lambda name: False)

    with caplog.at_level("INFO"):
        restore_command.restore("demo", str(sql_path), force=True)

    assert "demo: service container is not running; start it first" in caplog.text


def test_restore_no_sources_found_exits_cleanly(
    monkeypatch: pytest.MonkeyPatch,
    caplog: pytest.LogCaptureFixture,
    tmp_path: Path,
) -> None:
    services_dir = tmp_path / "services"
    services_dir.mkdir()
    (tmp_path / ".env").write_text(
        "DB_POSTGRES_VERSION=18\n"
        "DB_REMOTE_HOST=2.26.53.128\n"
        "DB_REMOTE_USER=root\n"
        "DB_REMOTE_PASSWORD=secret\n"
        "DB_REMOTE_BACKUP_PATH=/root/backups\n",
        encoding="utf-8",
    )
    (services_dir / ".env.demo").write_text(
        "POSTGRES_USER=admin\n"
        "POSTGRES_PASSWORD=secret\n"
        "POSTGRES_PORT=5401\n",
        encoding="utf-8",
    )

    class FakeSession:
        def __enter__(self):
            return self

        def __exit__(self, exc_type, exc, tb):
            return None

    monkeypatch.chdir(tmp_path)
    monkeypatch.setattr(restore_command, "open_remote_session", lambda *args, **kwargs: FakeSession())
    monkeypatch.setattr(restore_command, "list_remote_restore_sources", lambda *args, **kwargs: [])

    with caplog.at_level("INFO"):
        restore_command.restore("demo", None, force=False)

    assert "No restore sources found for demo" in caplog.text


def test_restore_remote_selection_reprompts_and_cleans_temp_download(
    monkeypatch: pytest.MonkeyPatch,
    tmp_path: Path,
) -> None:
    services_dir = tmp_path / "services"
    services_dir.mkdir()
    temp_download = tmp_path / "temp.sql.gz"
    temp_download.write_bytes(b"compressed")
    (tmp_path / ".env").write_text(
        "DB_POSTGRES_VERSION=18\n"
        "DB_REMOTE_HOST=2.26.53.128\n"
        "DB_REMOTE_USER=root\n"
        "DB_REMOTE_PASSWORD=secret\n"
        "DB_REMOTE_BACKUP_PATH=/root/backups\n",
        encoding="utf-8",
    )
    (services_dir / ".env.demo").write_text(
        "POSTGRES_USER=admin\n"
        "POSTGRES_PASSWORD=secret\n"
        "POSTGRES_PORT=5401\n",
        encoding="utf-8",
    )

    prompts = iter(["x", "5", "1"])
    calls: list[str] = []

    class FakeSession:
        def __enter__(self):
            return self

        def __exit__(self, exc_type, exc, tb):
            return None

    monkeypatch.chdir(tmp_path)
    monkeypatch.setattr(restore_command.typer, "prompt", lambda *args, **kwargs: next(prompts))
    monkeypatch.setattr(restore_command.typer, "confirm", lambda *args, **kwargs: True)
    monkeypatch.setattr(restore_command, "open_remote_session", lambda *args, **kwargs: FakeSession())
    monkeypatch.setattr(
        restore_command,
        "list_remote_restore_sources",
        lambda *args, **kwargs: [
            restore_ops.RestoreSource(
                kind="remote",
                display_name="demo.sql.gz",
                path=None,
                remote_path="/root/backups/demo.sql.gz",
                size_bytes=100,
                mtime_epoch=10,
            )
        ],
    )
    monkeypatch.setattr(restore_command, "container_is_running", lambda name: True)
    monkeypatch.setattr(restore_command, "query_database_size", lambda *args, **kwargs: 100)
    monkeypatch.setattr(restore_command, "download_remote_restore", lambda *args, **kwargs: temp_download)
    monkeypatch.setattr(
        restore_command,
        "terminate_service_connections",
        lambda *args, **kwargs: calls.append("terminate"),
    )
    monkeypatch.setattr(
        restore_command,
        "drop_and_recreate_service_database",
        lambda *args, **kwargs: calls.append("recreate"),
    )
    monkeypatch.setattr(
        restore_command,
        "restore_gzip_file",
        lambda *args, **kwargs: calls.append("gzip"),
    )

    restore_command.restore("demo", None, force=False)

    assert calls == ["terminate", "recreate", "gzip"]
    assert not temp_download.exists()


def test_restore_force_false_decline_leaves_database_untouched(
    monkeypatch: pytest.MonkeyPatch,
    tmp_path: Path,
) -> None:
    services_dir = tmp_path / "services"
    services_dir.mkdir()
    sql_path = tmp_path / "dump.sql"
    sql_path.write_text("SELECT 1;", encoding="utf-8")
    (services_dir / ".env.demo").write_text(
        "POSTGRES_USER=admin\n"
        "POSTGRES_PASSWORD=secret\n"
        "POSTGRES_PORT=5401\n",
        encoding="utf-8",
    )

    monkeypatch.chdir(tmp_path)
    monkeypatch.setattr(restore_command, "container_is_running", lambda name: True)
    monkeypatch.setattr(restore_command, "query_database_size", lambda *args, **kwargs: 100)
    monkeypatch.setattr(restore_command.typer, "confirm", lambda *args, **kwargs: False)
    monkeypatch.setattr(
        restore_command,
        "terminate_service_connections",
        lambda *args, **kwargs: (_ for _ in ()).throw(AssertionError("terminate should not run")),
    )

    restore_command.restore("demo", str(sql_path), force=False)


def test_sizes_logs_when_no_services_found(
    monkeypatch: pytest.MonkeyPatch,
    caplog: pytest.LogCaptureFixture,
    tmp_path: Path,
) -> None:
    monkeypatch.chdir(tmp_path)
    monkeypatch.setattr(sizes_command, "load_all_service_configs", lambda project_root: [])

    with caplog.at_level("INFO"):
        sizes_command.sizes()

    assert "No services found" in caplog.text


def test_sizes_reports_running_and_stopped_services(
    monkeypatch: pytest.MonkeyPatch,
    caplog: pytest.LogCaptureFixture,
    tmp_path: Path,
) -> None:
    configs = [
        ServiceConfig(
            name="running_demo",
            env_path=tmp_path / "services" / ".env.running_demo",
            postgres_user="admin",
            postgres_password="secret",
            postgres_port=5401,
        ),
        ServiceConfig(
            name="stopped_demo",
            env_path=tmp_path / "services" / ".env.stopped_demo",
            postgres_user="admin",
            postgres_password="secret",
            postgres_port=5402,
        ),
    ]

    monkeypatch.chdir(tmp_path)
    monkeypatch.setattr(sizes_command, "load_all_service_configs", lambda project_root: configs)
    monkeypatch.setattr(
        sizes_command,
        "container_is_running",
        lambda name: name == "running_demo",
    )
    monkeypatch.setattr(
        sizes_command,
        "query_database_size",
        lambda container_name, service_config: 7861951,
    )

    with caplog.at_level("INFO"):
        sizes_command.sizes()

    assert "running_demo: 0.01 GB" in caplog.text
    assert "stopped_demo: stopped, start the service first" in caplog.text


def test_sizes_propagates_query_errors(
    monkeypatch: pytest.MonkeyPatch,
    tmp_path: Path,
) -> None:
    configs = [
        ServiceConfig(
            name="broken_demo",
            env_path=tmp_path / "services" / ".env.broken_demo",
            postgres_user="admin",
            postgres_password="secret",
            postgres_port=5401,
        ),
    ]

    monkeypatch.chdir(tmp_path)
    monkeypatch.setattr(sizes_command, "load_all_service_configs", lambda project_root: configs)
    monkeypatch.setattr(sizes_command, "container_is_running", lambda name: True)
    monkeypatch.setattr(
        sizes_command,
        "query_database_size",
        lambda container_name, service_config: (_ for _ in ()).throw(
            ValueError("broken size query")
        ),
    )

    with pytest.raises(ValueError, match="broken size query"):
        sizes_command.sizes()
