from __future__ import annotations

import re
from collections import defaultdict
from pathlib import Path
from typing import Iterable

import yaml

from ops.core.models import GlobalConfig, ServiceConfig

AUTOGENERATED_COMMENT = (
    "# Автоматически сгенерировано. Не редактировать. Используй db apply."
)
EMPTY_COMPOSE = {"services": {}}
POSTGRES_VERSION_PATTERN = re.compile(r"^(?P<major>\d+)")


def build_compose(
    global_config: GlobalConfig,
    service_configs: list[ServiceConfig],
) -> dict[str, object]:
    if not service_configs:
        raise ValueError("Cannot build compose.yaml without service configurations")

    validate_unique_ports(service_configs)
    shm_size = compute_shm_size_bytes(read_mem_total_bytes())
    postgres_data_dir = resolve_postgres_data_dir(global_config.postgres_version)

    services: dict[str, object] = {}
    for service_config in sorted(service_configs, key=lambda item: item.name):
        service_block: dict[str, object] = {
            "image": f"postgres:{global_config.postgres_version}",
            "container_name": service_config.name,
            "env_file": [
                {
                    "path": f"./services/.env.{service_config.name}",
                    "format": "raw",
                }
            ],
            "environment": {
                "POSTGRES_DB": service_config.name,
            },
            "ports": [f"{service_config.postgres_port}:5432"],
            "volumes": [f"./data/{service_config.name}:{postgres_data_dir}"],
            "restart": "unless-stopped",
            "healthcheck": {
                # Escape dollars so Compose passes the variables through to the container.
                "test": ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"],
                "interval": "10s",
                "timeout": "5s",
                "retries": 3,
                "start_period": "30s",
            },
            "shm_size": shm_size,
        }

        if service_config.max_connections is not None:
            service_block["command"] = [
                "postgres",
                "-c",
                f"max_connections={service_config.max_connections}",
            ]

        limits: dict[str, object] = {}
        if service_config.memory_limit:
            limits["memory"] = service_config.memory_limit
        if service_config.cpu_limit:
            limits["cpus"] = service_config.cpu_limit
        if limits:
            service_block["deploy"] = {"resources": {"limits": limits}}

        services[service_config.name] = service_block

    return {"services": services}


def write_compose(project_root: Path, compose_dict: dict[str, object]) -> Path:
    compose_path = project_root / "compose.yaml"
    yaml_payload = yaml.safe_dump(
        compose_dict,
        sort_keys=False,
        allow_unicode=False,
    )
    compose_path.write_text(
        f"{AUTOGENERATED_COMMENT}\n{yaml_payload}",
        encoding="utf-8",
    )
    return compose_path


def write_empty_compose(project_root: Path) -> Path:
    return write_compose(project_root, EMPTY_COMPOSE)


def validate_unique_ports(service_configs: Iterable[ServiceConfig]) -> None:
    ports_to_services: dict[int, list[str]] = defaultdict(list)
    for service_config in service_configs:
        ports_to_services[service_config.postgres_port].append(service_config.name)

    conflicts = {
        port: names
        for port, names in ports_to_services.items()
        if len(names) > 1
    }
    if conflicts:
        details = ", ".join(
            f"{port} -> {', '.join(sorted(names))}"
            for port, names in sorted(conflicts.items())
        )
        raise ValueError(f"Found conflicting PostgreSQL ports: {details}")


def read_mem_total_bytes(proc_meminfo_path: Path = Path("/proc/meminfo")) -> int:
    with proc_meminfo_path.open("r", encoding="utf-8") as handle:
        for raw_line in handle:
            if raw_line.startswith("MemTotal:"):
                parts = raw_line.split()
                return int(parts[1]) * 1024

    raise ValueError(f"{proc_meminfo_path}: MemTotal was not found")


def compute_shm_size_bytes(total_memory_bytes: int) -> int:
    return total_memory_bytes * 9 // 10


def resolve_postgres_data_dir(postgres_version: str) -> str:
    match = POSTGRES_VERSION_PATTERN.match(postgres_version.strip())
    if not match:
        raise ValueError(
            "DB_POSTGRES_VERSION must start with a PostgreSQL major version"
        )

    major_version = int(match.group("major"))
    if major_version >= 18:
        return f"/var/lib/postgresql/{major_version}/docker"
    return "/var/lib/postgresql/data"
